# Author : Benjamin Pope
# Date : 23/2/2024
# Title : tests.yml
# Description : Automatically runs tests when branches are merged.
#   The tests that are run can be found in the tests directory.

name: automated tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64

      - name: create environment
        run: |
          uv venv --python 3.11 .venv
          uv pip install --python .venv/bin/python -e . pytest ruff mkdocs mkdocstrings mkdocstrings[python] mkdocs-material mkdocs-jupyter

      - name: Lint (Ruff)
        run: |
          uv run --python .venv/bin/python ruff check --force-exclude .
          uv run --python .venv/bin/python ruff format --force-exclude --check .

      # ===== Tests =====
      - name: Test Suite
        run: uv run --python .venv/bin/python pytest

      - name: Docs Build (strict)
        run: uv run --python .venv/bin/python mkdocs build --strict

